<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>@yield('title', 'AssistMyHR')</title>
<style>
:root{font-family:system-ui,sans-serif;color:#17233b;background:#f3f6fb}*{box-sizing:border-box}body{margin:0}header{background:white;border-bottom:1px solid #dce3ed;padding:20px max(24px,calc((100% - 1120px)/2));display:flex;gap:24px;align-items:center;flex-wrap:wrap}header a{color:#173a74;text-decoration:none}header strong{font-size:21px;margin-right:auto}main{max-width:1120px;margin:38px auto;padding:0 24px}h1{font-size:30px;margin:0 0 12px}h2{font-size:20px}p{line-height:1.6}.muted{color:#627087}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:20px}.card{background:white;padding:24px;border:1px solid #dde5ef;border-radius:12px;margin-bottom:22px}.narrow{max-width:560px;margin:auto}label{display:block;margin:14px 0 6px;font-weight:600;font-size:14px}input,select,textarea{font:inherit;width:100%;padding:10px;border:1px solid #b9c7d9;border-radius:6px;background:white}textarea{min-height:80px}button,.button{font:inherit;display:inline-block;border:0;border-radius:7px;background:#2563eb;color:white;padding:11px 18px;text-decoration:none;cursor:pointer;margin-top:16px}.secondary{background:#e7eef9;color:#21477f}.notice{background:#e6f5ec;border:1px solid #abd3b9;padding:15px;border-radius:8px;margin-bottom:20px}.error{background:#fff0ee;border-color:#e6b5ad;color:#8b251b}table{border-collapse:collapse;width:100%;text-align:left}th,td{padding:12px;border-bottom:1px solid #e3e9f0;vertical-align:top}th{font-size:12px;text-transform:uppercase;color:#637087}.scroll{overflow:auto}.metric{font-size:32px;font-weight:700}.badge{font-size:13px;background:#edf2fa;padding:5px 9px;border-radius:5px}.inline{display:inline}.inline button{margin:0}.fields{display:grid;grid-template-columns:1fr 1fr;gap:14px}a{color:#225bba}code{overflow-wrap:anywhere}footer{margin-top:36px;color:#637087;font-size:13px}@media(max-width:600px){.fields{grid-template-columns:1fr}main{padding:0 16px}header{padding:16px}}
</style></head><body><header><strong><a href="/">AssistMyHR</a></strong>
@if(auth('platform')->check() && request()->is('superadmin*'))
<a href="{{ route('superadmin.dashboard') }}">Clients</a><a href="{{ route('superadmin.plans') }}">Plans</a><a href="{{ route('superadmin.settings') }}">Settings</a><form class="inline" method="post" action="{{ route('superadmin.logout') }}">@csrf<button class="secondary">Sign out</button></form>
@else
<a href="{{ route('saas.pricing') }}">Plans</a><a href="{{ route('register') }}">Create account</a><a href="{{ tenant_route('login') }}">ATS login</a>
@endif</header><main>
@if(session('status'))<div class="notice" role="status">{{ session('status') }}</div>@endif
@if($errors->any())<div class="notice error" role="alert">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
@yield('content')<footer>AssistMyHR · Recruitment workspace</footer></main></body></html>
