@extends('saas.platform-layout')
@push('head-script')
<style>
.pd-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px;margin-bottom:26px}.pd-stat{background:white;border:1px solid #e2e8f0;border-radius:18px;padding:22px;display:flex;align-items:center;gap:16px}.pd-icon{width:46px;height:46px;border-radius:13px;display:grid;place-items:center;background:#eff6ff;color:#2563eb;font-size:22px}.pd-value{font-size:30px;line-height:1.2;font-weight:750;color:#17233b}.pd-label{font-size:12px;color:#64748b;margin-top:6px}.pd-stat:first-child{background:#112240;border-color:#112240}.pd-stat:first-child .pd-value{color:white}.pd-stat:first-child .pd-label{color:#bac9e2}.pd-stat:first-child .pd-icon{background:#263c60;color:white}.pd-toolbar{display:flex;justify-content:space-between;align-items:center;gap:18px;padding-bottom:22px}.pd-toolbar h2{margin:0}.pd-search{width:300px;max-width:100%;border:1px solid #e2e8f0;border-radius:12px;padding:12px 16px;background:#f8fafc}.pd-client{display:flex;align-items:center;gap:12px}.pd-avatar{width:40px;height:40px;flex-shrink:0;display:grid;place-items:center;background:#eff6ff;color:#2563eb;border-radius:12px;font-weight:700}.pd-badge{display:inline-block;border-radius:20px;padding:5px 12px;background:#f1f5f9;color:#475569;font-size:12px;font-weight:600}.pd-badge.active{background:#ecfdf5;color:#047857}.pd-badge.suspended,.pd-badge.failed{background:#fff1f2;color:#be123c}.pd-plan{background:#eff6ff;color:#2563eb}.pd-open{font-weight:600;white-space:nowrap}.pd-clients small{color:#94a3b8}.pd-clients.card{box-shadow:none;border:1px solid #e2e8f0}.pd-clients td{vertical-align:middle}.pd-intro{display:flex;justify-content:space-between;align-items:center;margin-bottom:22px;gap:16px}.pd-intro p{margin:0}.pd-intro a{font-size:13px;font-weight:600}.pd-clients [hidden]{display:none!important}@media(max-width:1100px){.pd-summary{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.pd-summary{grid-template-columns:1fr}.pd-toolbar,.pd-intro{align-items:flex-start;flex-direction:column}.pd-search{width:100%}}
</style>
@endpush
@section('platform-content')
<div class="pd-intro"><p class="muted">Your platform at a glance. Manage clients and subscriptions in one place.</p><a href="{{ route('superadmin.plans') }}">Manage plans &rarr;</a></div>
<div class="pd-summary">@foreach([['Total clients',$total,'&#9783;'],['Active workspaces',$active,'&#10003;'],['Suspended',$suspended,'&#8214;'],['Expired subscriptions',$expired,'&#9201;']] as $stat)<div class="pd-stat"><span class="pd-icon" aria-hidden="true">{!! $stat[2] !!}</span><div><div class="pd-value">{{ $stat[1] }}</div><div class="pd-label">{{ $stat[0] }}</div></div></div>@endforeach</div>
<div id="clients" class="card pd-clients"><div class="pd-toolbar"><div><h2>Client directory</h2><small>{{ $total }} registered clients</small></div><input class="pd-search" id="client-search" type="search" placeholder="Search this page..." aria-label="Search clients on this page"></div><div class="scroll"><table><thead><tr><th>Client</th><th>Owner</th><th>Status</th><th>Plan</th><th>Expiry</th><th>Action</th></tr></thead><tbody>@forelse($tenants as $tenant)<tr data-client-row><td><div class="pd-client"><span class="pd-avatar" aria-hidden="true">{{ mb_substr($tenant->name,0,1) }}</span><div><a href="{{ route('superadmin.tenants.show',$tenant) }}">{{ $tenant->name }}</a><br><small>{{ $tenant->slug }}</small></div></div></td><td>{{ $tenant->owner_email }}</td><td><span class="pd-badge {{ $tenant->status }}">{{ ucfirst($tenant->status) }}</span></td><td><span class="pd-badge pd-plan">{{ $tenant->subscription?->plan?->name ?? 'Pending' }}</span></td><td>{{ $tenant->subscription?->expires_at?->format('d M Y') ?? 'No expiry' }}</td><td><a class="pd-open" href="{{ route('superadmin.tenants.show',$tenant) }}">Manage &rarr;</a></td></tr>@empty<tr><td colspan="6">No clients yet.</td></tr>@endforelse<tr id="client-no-results" hidden><td colspan="6">No matching clients on this page.</td></tr></tbody></table></div>{{ $tenants->links() }}</div>
<script>document.getElementById('client-search').addEventListener('input',function(){const query=this.value.toLowerCase().trim();let visible=0;document.querySelectorAll('[data-client-row]').forEach(row=>{row.hidden=!row.textContent.toLowerCase().includes(query);if(!row.hidden)visible++});document.getElementById('client-no-results').hidden=!query||visible>0});</script>
@endsection
