@extends('saas.platform-layout')
@push('head-script')
<style>.platform-content .plans-toolbar{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:26px}.platform-content .plans-toolbar p{margin:0;max-width:700px}.platform-content .plans-toolbar button{margin:0;white-space:nowrap}.platform-content .plans-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:22px}.platform-content .plan-card{display:flex;flex-direction:column;margin:0;padding:28px;min-width:0}.platform-content .plan-card h2{font-size:21px;margin:20px 0 10px}.platform-content .plan-price{font-size:34px;font-weight:800;letter-spacing:-1px;margin:8px 0;overflow-wrap:anywhere}.platform-content .plan-price small{font-size:12px;font-weight:600;color:#8892a0;letter-spacing:0}.platform-content .plan-status{display:flex;flex-wrap:wrap;gap:8px}.platform-content .plan-chip{font-size:10px;font-weight:700;padding:5px 9px;border-radius:8px;background:#ecfdf5;color:#047857}.platform-content .plan-chip.private{background:#f3f4f6;color:#6b7280}.platform-content .plan-chip.disabled{background:#fff1f2;color:#be123c}.platform-content .plan-features{list-style:none;padding:18px 0;margin:18px 0 0;border-top:1px solid #f0eee9;flex:1}.platform-content .plan-features li{display:flex;justify-content:space-between;gap:15px;color:#5a6478;font-size:12px;padding:10px 0}.platform-content .plan-features strong{color:#1a1e2e}.platform-content .plan-card button{width:100%}.platform-content .plan-dialog{width:min(700px,calc(100% - 32px));max-height:90vh;padding:26px;border:1px solid #e8e6e1;border-radius:20px;color:#1a1e2e;overflow:auto;box-shadow:0 25px 80px #10213f30}.platform-content .plan-dialog::backdrop{background:#10213f80;backdrop-filter:blur(3px)}.platform-content .dialog-header{display:flex;justify-content:space-between;align-items:center;gap:15px}.platform-content .dialog-header h2{font-size:20px;margin:0}.platform-content .dialog-header button{margin:0;background:#f3f4f6;color:#5a6478;padding:8px 12px}.platform-content .plan-empty{padding:40px;text-align:center}@media(max-width:640px){.platform-content .plans-toolbar{flex-direction:column;align-items:flex-start}.platform-content .plan-dialog{padding:20px}}</style>
@endpush
@section('platform-content')
<div class="plans-toolbar"><p class="muted">Manage client plans and capacity limits. Plan changes also apply to clients already assigned to that plan. Billing is managed manually.</p><button type="button" data-plan-open="plan-new">+ Create plan</button></div>
<div class="plans-grid">@forelse($plans as $plan)<article class="card plan-card"><div class="plan-status"><span class="plan-chip {{ $plan->enabled ? '' : 'disabled' }}">{{ $plan->enabled ? 'Enabled' : 'Disabled' }}</span><span class="plan-chip private">{{ $plan->public ? 'Public plan' : 'Private plan' }}</span></div><h2>{{ $plan->name }}</h2><p class="plan-price"><small>{{ $plan->currency }}</small> {{ number_format($plan->price,2) }}</p><p class="muted">Monthly reference price</p><ul class="plan-features">@foreach(['max_users'=>'Team members','max_jobs'=>'Stored jobs','max_candidates'=>'Candidates','storage_mb'=>'Storage'] as $field=>$label)<li><span>{{ $label }}</span><strong>{{ $plan->$field === null ? 'Unlimited' : number_format($plan->$field).($field==='storage_mb' ? ' MB' : '') }}</strong></li>@endforeach</ul><button class="secondary" type="button" data-plan-open="plan-{{ $plan->id }}">Edit plan</button></article>@empty<div class="card plan-empty"><h2>No plans yet</h2><p class="muted">Create your first client subscription plan to get started.</p></div>@endforelse</div>
@foreach($plans as $plan)<dialog class="plan-dialog" id="plan-{{ $plan->id }}" aria-labelledby="plan-title-{{ $plan->id }}"><div class="dialog-header"><h2 id="plan-title-{{ $plan->id }}">Edit {{ $plan->name }}</h2><button type="button" data-plan-close aria-label="Close plan editor">✕</button></div><form method="post" action="{{ route('superadmin.plans.update',$plan) }}">@include('saas.plan-form',['plan'=>$plan])</form></dialog>@endforeach
<dialog class="plan-dialog" id="plan-new" aria-labelledby="plan-title-new"><div class="dialog-header"><h2 id="plan-title-new">Create plan</h2><button type="button" data-plan-close aria-label="Close plan editor">✕</button></div><form method="post" action="{{ route('superadmin.plans.store') }}">@include('saas.plan-form',['plan'=>null])</form></dialog>
@endsection
@push('footer-script')
<script>
document.querySelectorAll('[data-plan-open]').forEach(button=>button.addEventListener('click',()=>document.getElementById(button.dataset.planOpen)?.showModal()));
document.querySelectorAll('[data-plan-close]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
@if($errors->any() && old('_plan_editor'))
const editor = document.getElementById('plan-' + @json(old('_plan_editor'))); if(editor) editor.showModal();
@endif
</script>
@endpush
