@extends('layouts.app')
@section('page-subtitle', 'Manage your clients, subscription plans and platform settings.')
@push('head-script')
@include('admin.partials.settings-design-styles')
<style>
.platform-content{padding-bottom:24px;color:#1A1E2E;font-size:13.5px}.platform-content p{line-height:1.7;margin-bottom:14px}.platform-content h2{font-size:15px;font-weight:700;margin-bottom:14px}.platform-content .muted{color:#8892A0;font-size:12.5px}.platform-content .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:20px}.platform-content .card{border:1px solid #E8E6E1;border-radius:18px;background:#fff;padding:24px;margin-bottom:20px}.platform-content .metric{font-size:32px;font-weight:800;letter-spacing:-1px;margin-top:8px}.platform-content .fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.platform-content label{display:block;font-size:11.5px;font-weight:700;color:#5A6478;margin:14px 0 6px}.platform-content input,.platform-content select,.platform-content textarea{width:100%;border:1.5px solid #E2DED8;border-radius:11px;padding:10px 14px;font-size:13.5px;background:white;color:#1A1E2E;outline:none}.platform-content input:focus,.platform-content select:focus,.platform-content textarea:focus{border-color:#2563EB;box-shadow:0 0 0 3px rgba(37,99,235,.09)}.platform-content input[readonly]{background:#F8F9FB;color:#5A6478}.platform-content textarea{min-height:90px}.platform-content button,.platform-content .button{display:inline-flex;align-items:center;justify-content:center;background:#2563EB;border:0;border-radius:12px;color:#fff;font-size:12.5px;font-weight:600;padding:10px 18px;margin-top:16px;text-decoration:none;cursor:pointer}.platform-content button:hover,.platform-content .button:hover{background:#1d4ed8}.platform-content .secondary{background:#EFF6FF;color:#2563EB}.platform-content .scroll{overflow:auto}.platform-content table{border-collapse:collapse;width:100%;text-align:left}.platform-content th{background:#F8F9FB;font-size:10.5px;text-transform:uppercase;letter-spacing:.04em;color:#8892A0;font-weight:700}.platform-content th,.platform-content td{padding:14px 16px;border-bottom:1px solid #F0EEE9;vertical-align:top}.platform-content tbody tr:hover{background:#FAFBFD}.platform-content a:not(.button){color:#2563EB;font-weight:600}.platform-content .badge{display:inline-flex;border-radius:8px;background:#EFF6FF;color:#2563EB;padding:4px 9px;font-size:11px;font-weight:600}.platform-content .notice{border-radius:12px;background:#ecfdf5;border:1px solid #a7f3d0;padding:14px 18px;margin-bottom:20px}.platform-content .error{background:#fff1f2;border-color:#fecdd3;color:#9f1239}.platform-content small{font-size:11px;overflow-wrap:anywhere}.platform-content .narrow{max-width:700px}@media(max-width:640px){.platform-content .fields{grid-template-columns:1fr}.platform-content .card{padding:18px}}
</style>
@endpush
@section('content')
<div class="platform-content">
@if(session('status'))<div class="notice" role="status">{{ session('status') }}</div>@endif
@if($errors->any())<div class="notice error" role="alert">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
@yield('platform-content')
</div>
@endsection
