@extends('saas.platform-layout')
@section('platform-content')
<p class="muted">{{ $tenant->owner_email }} · {{ $tenant->slug }} · Created {{ $tenant->created_at?->format('d M Y') }}</p><div class="card"><p>Workspace: {{ $tenant->status }} · Plan: {{ $tenant->subscription?->plan?->name ?? 'Unavailable' }} · Subscription: {{ $tenant->subscription?->status ?? 'Unavailable' }}<br>Expiry: {{ $tenant->subscription?->expires_at ? $tenant->subscription->expires_at->format('d M Y H:i').' UTC' : 'No expiry' }}</p>
@if($usage)<p>{{ $usage['users'] }} users · {{ $usage['jobs'] }} jobs · {{ $usage['candidates'] }} candidates · {{ number_format($usage['storage_bytes']/1048576, 1) }} MB local files</p>@else<p class="notice error">Usage could not be loaded. Check the workspace database configuration.</p>@endif<label class="bs-set-lbl">Client login URL</label><input class="bs-f-input" readonly value="{{ route('saas.workspace', $tenant->slug) }}"></div>
@if($tenant->subscription)<div class="grid"><div class="card"><h2>Extend subscription manually</h2><p class="muted">Add days from the current expiry (or today if expired), or set a later expiry date. The reason is recorded.</p><form method="post" action="{{ route('superadmin.tenants.extend', $tenant) }}">@csrf<label class="bs-set-lbl">Add days</label><input class="bs-f-input" name="days" type="number" min="1" max="3650" value="{{ old('days') }}"><label class="bs-set-lbl">Or set expiry date</label><input class="bs-f-input" name="expires_at" type="date" value="{{ old('expires_at') }}"><label class="bs-set-lbl">Optional plan change</label><select class="bs-f-sel" name="plan_id"><option value="">Keep current plan</option>@foreach($plans as $plan)<option value="{{ $plan->id }}">{{ $plan->name }}</option>@endforeach</select><label class="bs-set-lbl">Reason</label><textarea class="bs-f-textarea" name="reason" required maxlength="1000"></textarea><button>Extend subscription</button></form></div>
<div class="card"><h2>Change plan</h2><p class="muted">Changing the plan preserves the current expiry.</p><form method="post" action="{{ route('superadmin.tenants.plan', $tenant) }}">@csrf<label class="bs-set-lbl">Plan</label><select class="bs-f-sel" name="plan_id" required>@foreach($plans as $plan)<option value="{{ $plan->id }}" @selected($tenant->subscription->plan_id === $plan->id)>{{ $plan->name }}</option>@endforeach</select><label class="bs-set-lbl">Reason</label><textarea class="bs-f-textarea" name="reason" required maxlength="1000"></textarea><button>Update plan</button></form></div></div>@endif
@if(!in_array($tenant->status,['failed','provisioning']))<div class="grid"><div class="card"><h2>Workspace access</h2><form method="post" action="{{ route('superadmin.tenants.update', $tenant) }}">@csrf @method('PUT')<label class="bs-set-lbl">Status</label><select class="bs-f-sel" name="status"><option value="active" @selected($tenant->status==='active')>Active</option><option value="suspended" @selected($tenant->status==='suspended')>Suspended</option></select><label class="bs-set-lbl">Reason</label><textarea class="bs-f-textarea" name="reason" required maxlength="1000"></textarea><button>Update access</button></form></div><div class="card"><h2>Approve owner email</h2><p class="muted">Use only after independently confirming the owner's identity if email delivery is unavailable.</p><form method="post" action="{{ route('superadmin.tenants.verify-owner',$tenant) }}">@csrf<label class="bs-set-lbl">Verification reason</label><textarea class="bs-f-textarea" name="reason" required maxlength="1000"></textarea><button class="secondary">Approve owner email</button></form></div></div>@endif
<div class="card"><h2>Audit history</h2>@include('saas.audit', ['logs'=>$logs])</div>
@endsection
