@extends('saas.public-layout')
@section('title', 'Create your ATS workspace | AssistMyHR')
@section('content')
<div class="signup"><aside class="signup-story"><span class="eyebrow">Your next great hire starts here</span><h1>Build your team.<br><em>Simplify your hiring.</em></h1><p>A dedicated recruitment workspace for your company, from the first application to the final offer.</p><ul class="features"><li>Organize jobs and candidates in one place</li><li>Bring your recruiting team together</li><li>Keep company data in a separate workspace</li></ul><p>Start with a trial. Grow at your own pace.</p></aside><section class="signup-form" aria-labelledby="signup-title"><h2 id="signup-title">Create your ATS workspace</h2><p class="muted">Tell us a little about your company to get started.</p><form method="post" action="{{ route('register') }}">@csrf
<div class="field"><label for="company_name">Company name</label><input id="company_name" name="company_name" value="{{ old('company_name') }}" placeholder="Your company" required maxlength="150" autocomplete="organization" @error('company_name') aria-invalid="true" aria-describedby="company_name-error" @enderror>@error('company_name')<p class="field-error" id="company_name-error">{{ $message }}</p>@enderror</div>
<div class="field"><label for="slug">Workspace name</label><input id="slug" name="slug" value="{{ old('slug') }}" pattern="[a-z0-9][a-z0-9-]{1,49}" placeholder="your-company" required minlength="2" maxlength="50" autocapitalize="none" spellcheck="false" aria-describedby="slug-hint @error('slug') slug-error @enderror" @error('slug') aria-invalid="true" @enderror><p class="hint" id="slug-hint">Use lowercase letters, numbers and hyphens. Your login link: {{ url('/saas/workspace') }}/your-company</p>@error('slug')<p class="field-error" id="slug-error">{{ $message }}</p>@enderror</div>
<div class="fields"><div class="field"><label for="name">Your name</label><input id="name" name="name" value="{{ old('name') }}" placeholder="Full name" required maxlength="150" autocomplete="name" @error('name') aria-invalid="true" aria-describedby="name-error" @enderror>@error('name')<p class="field-error" id="name-error">{{ $message }}</p>@enderror</div><div class="field"><label for="email">Work email</label><input id="email" name="email" type="email" value="{{ old('email') }}" placeholder="you@company.com" required maxlength="254" autocomplete="email" @error('email') aria-invalid="true" aria-describedby="email-error" @enderror>@error('email')<p class="field-error" id="email-error">{{ $message }}</p>@enderror</div></div>
<div class="fields"><div class="field"><label for="password">Password</label><input id="password" name="password" type="password" required minlength="12" maxlength="200" autocomplete="new-password" aria-describedby="password-hint @error('password') password-error @enderror" @error('password') aria-invalid="true" @enderror><p class="hint" id="password-hint">Use at least 12 characters.</p>@error('password')<p class="field-error" id="password-error">{{ $message }}</p>@enderror</div><div class="field"><label for="password_confirmation">Confirm password</label><input id="password_confirmation" name="password_confirmation" type="password" required minlength="12" maxlength="200" autocomplete="new-password" @error('password_confirmation') aria-invalid="true" aria-describedby="password_confirmation-error" @enderror>@error('password_confirmation')<p class="field-error" id="password_confirmation-error">{{ $message }}</p>@enderror</div></div>
<button class="button" type="submit">Create workspace <span aria-hidden="true">&nbsp;→</span></button><p class="login-note">Already have a workspace? <a href="{{ tenant_route('login') }}">Sign in</a></p></form></section></div>
@endsection
