@extends('saas.public-layout')
@section('title', $tenant->name.' subscription | AssistMyHR')
@section('content')
<style>
.subscription-heading{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:28px}.subscription-heading h1{font-size:32px;margin:14px 0 8px}.subscription-heading p{margin:0}.subscription-grid{display:grid;grid-template-columns:1fr 1.25fr;gap:24px;margin-bottom:24px}.subscription-card{background:#fff;border:1px solid #e8e6e1;border-radius:22px;padding:28px;min-width:0;box-shadow:0 8px 28px rgba(20,36,66,.035)}.plan-summary{background:radial-gradient(ellipse at top right,#2563eb35,transparent 75%),#10213f;color:white}.plan-summary h2{font-size:30px;margin:22px 0}.plan-summary .muted{color:#b1bed3}.status-chip{display:inline-flex;border-radius:30px;padding:6px 11px;font-size:11px;font-weight:700;background:#eef2ff;color:#4338ca}.status-chip.available{background:#ecfdf5;color:#047857}.status-chip.paused{background:#fff1f2;color:#be123c}.subscription-details{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:24px 0}.subscription-details dt{font-size:11px;color:#b1bed3;margin-bottom:8px}.subscription-details dd{margin:0;font-size:13px;line-height:1.6}.usage-row{margin-top:22px}.usage-label{display:flex;justify-content:space-between;gap:12px;font-size:12px;color:#5a6478;margin-bottom:10px}.usage-label strong{color:#1a1e2e}.usage-track{height:6px;border-radius:10px;background:#eef0f5;overflow:hidden}.usage-fill{height:100%;background:#2563eb;border-radius:10px}.usage-fill.full{background:#e11d48}.workspace-link{margin-top:26px;padding-top:22px;border-top:1px solid #eeedf2}.renewal-grid{display:grid;grid-template-columns:.85fr 1.15fr;gap:36px}.renewal-grid p{margin:0}.subscription-card select,.subscription-card textarea{width:100%;font:400 13px 'Plus Jakarta Sans',sans-serif;border:1.5px solid #e2ded8;border-radius:11px;padding:12px 14px;background:#fff;color:#1a1e2e}.subscription-card textarea{resize:vertical;min-height:110px}.subscription-card select:focus,.subscription-card textarea:focus{outline:3px solid #2563eb17;border-color:#2563eb}.subscription-card form .field{margin-bottom:20px}.subscription-empty{padding:18px;background:#f8f9fc;border-radius:12px;font-size:13px;color:#7b8597}@media(max-width:780px){.subscription-grid,.renewal-grid{grid-template-columns:1fr}.subscription-heading{align-items:flex-start;flex-direction:column}.subscription-card{padding:24px}.subscription-heading h1{font-size:28px}}
</style>
@php($subscription = $tenant->subscription)
@php($plan = $subscription?->plan)
<div class="subscription-heading"><div><span class="eyebrow">Your subscription</span><h1>{{ $tenant->name }}</h1><p class="muted">Manage your plan, review usage and request a renewal.</p></div>@if($tenant->hasAccess())<a class="button" href="{{ tenant_route('admin.dashboard') }}">Open ATS <span aria-hidden="true">&nbsp;→</span></a>@endif</div>
<div class="subscription-grid"><section class="subscription-card plan-summary" aria-labelledby="current-plan"><span class="eyebrow">Current plan</span><h2 id="current-plan">{{ $plan?->name ?? 'No plan' }}</h2><span class="status-chip {{ $tenant->hasAccess() ? 'available' : 'paused' }}">{{ ucfirst($subscription?->status ?? 'Unavailable') }}</span><dl class="subscription-details"><div><dt>Workspace status</dt><dd>{{ ucfirst($tenant->status) }}</dd></div><div><dt>Expires on</dt><dd>{{ $subscription?->expires_at ? $subscription->expires_at->format('d M Y') : 'No expiry' }}@if($subscription?->expires_at)<br><span class="muted">{{ $subscription->expires_at->format('H:i') }} UTC</span>@endif</dd></div></dl>@if(!$tenant->hasAccess())<div class="notice error" role="status">Your ATS access is paused. Contact the administrator for renewal or reactivation.</div>@else<p class="muted">Your workspace is ready. Continue managing your recruitment in the ATS.</p>@endif</section>
<section class="subscription-card" aria-labelledby="usage-title"><h2 id="usage-title">Workspace usage</h2><p class="muted">Your current usage against this plan's limits.</p>
@foreach([['Team members',$usage['users'],$plan?->max_users,''],['Stored jobs',$usage['jobs'],$plan?->max_jobs,''],['Candidates',$usage['candidates'],$plan?->max_candidates,''],['Local storage',$usage['storage_bytes']/1048576,$plan?->storage_mb,' MB']] as [$label,$used,$limit,$unit])
@php($percentage = $limit > 0 ? min(100, max(0, $used / $limit * 100)) : null)
<div class="usage-row"><div class="usage-label"><strong>{{ $label }}</strong><span>{{ $unit ? number_format($used,1) : number_format($used) }}{{ $unit }} / {{ $limit !== null ? number_format($limit).$unit : 'Unlimited' }}</span></div>@if($percentage !== null)<div class="usage-track" role="progressbar" aria-label="{{ $label }} usage" aria-valuemin="0" aria-valuemax="100" aria-valuenow="{{ round($percentage) }}"><div class="usage-fill {{ $percentage >= 100 ? 'full' : '' }}" style="width:{{ $percentage }}%"></div></div>@endif</div>
@endforeach
<div class="workspace-link"><label for="company-login">Your company login link</label><input id="company-login" readonly value="{{ route('saas.workspace', $tenant->slug) }}"><p class="hint">Share this link with your recruiting team.</p></div></section></div>
@if(auth()->user()->cans('manage_settings'))<section class="subscription-card renewal-grid" aria-labelledby="renewal-title"><div><span class="eyebrow">Plan management</span><h2 id="renewal-title" style="margin-top:18px">Request a plan or renewal</h2><p class="muted">Choose a plan and tell us what you need. The platform administrator reviews your request and updates your subscription manually.</p><p class="hint" style="margin-top:16px">Submitting a request does not change your current plan immediately.</p></div><div>@if($plans->isNotEmpty())<form method="post" action="{{ tenant_route('saas.request-plan') }}">@csrf<div class="field"><label for="plan_id">Choose a plan</label><select id="plan_id" name="plan_id" required>@foreach($plans as $availablePlan)<option value="{{ $availablePlan->id }}" @selected(old('plan_id',$plan?->id)==$availablePlan->id)>{{ $availablePlan->name }} — {{ $availablePlan->currency }} {{ number_format($availablePlan->price,2) }}</option>@endforeach</select>@error('plan_id')<p class="field-error">{{ $message }}</p>@enderror</div><div class="field"><label for="reason">Message to the administrator</label><textarea id="reason" name="reason" required maxlength="1000" placeholder="Tell us about your plan change or renewal request…">{{ old('reason') }}</textarea>@error('reason')<p class="field-error">{{ $message }}</p>@enderror</div><button class="button" type="submit">Send request <span aria-hidden="true">&nbsp;→</span></button></form>@else<div class="subscription-empty">No public plans are available yet. Contact the platform administrator to renew your subscription.</div>@endif</div></section>@endif
@endsection
